### ISSUE TITLE
Certman Operator not working

### ISSUE THREAD

**Issue by kahootali** [openshift/certman-operator#140]
I have an Openshift 4.3.12 cluster, I deployed Hive on it and created an Openshift 4.3.2 cluster on Azure using Hive. My ClusterDeployment Instance has set installed to true. I deployed Certman Operator using the manifest given in deploy folder, without any tag so latest will have been deployed but Certman is not creating any CertificateRequest. The logs are 

```
{"level":"info","ts":1589193396.991396,"logger":"userMetrics","msg":"Metrics Route object updated Route.Name certman-operator and Route.Namespace certman-operator"}
{"level":"info","ts":1589193396.9914522,"logger":"cmd","msg":"Starting the Cmd."}
{"level":"info","ts":1589193431.2917986,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"clusterdeployment-controller"}
{"level":"info","ts":1589193431.2921095,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"certificaterequest-controller"}
{"level":"info","ts":1589193431.3921175,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"clusterdeployment-controller","worker count":1}
{"level":"info","ts":1589193431.3922951,"logger":"controller_clusterdeployment","msg":"reconciling ClusterDeployment","Request.Namespace":"cluster-azure","Request.Name":"openshift-cluster-azure"}
{"level":"info","ts":1589193431.392353,"logger":"controller_clusterdeployment","msg":"not a managed cluster","Request.Namespace":"cluster-azure","Request.Name":"openshift-cluster-azure"}
{"level":"info","ts":1589193431.3924532,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"certificaterequest-controller","worker count":1}
```

**Comment by c-e-brumm** [comment]
Hi @kahootali, thank you for the report and welcome to the project. 

Looking at the logs you provided it looks like the ClusterDeployment that it's attempting to reconcile is missing a label. Certman-Operator will skip over any ClusterDeployment that is missing `api.openshift.com/managed: "true"`. This is to make sure that it it only attempts to reconcile for clusters that are a part of the OpenShift Dedicated Platform, and not clusters self hosted clusters that were added to the OpenShift Cluster Manager dashboard and platform. If you're running your own Hive you will likely want to make sure that all your clusters get that label applied.

**Comment by kahootali** [comment]
Yeah this issue was solved, but I think there is some documentation gap, I will try to add to it. Thanks.
